[project]
name = "TechChallenge1ChurnTelco"
version = "0.1.0"
description = "Solução Completa para o Tech Challenge 1 da pós-graduação MLE da FIAP."
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi[standard]>=0.135.2",
    "matplotlib>=3.10.8",
    "optuna>=4.8.0",
    "pandas>=2.3.3",
    "scikit-learn>=1.8.0",
    "protobuf<5.0.0",
    "marimo>=0.23.3",
    "python-json-logger>=3.2.1",
]
authors = [
  {name = "Fernando Failla Foschiani", email = "fefailla68@gmail.com"}
]

[tool.setuptools.packages.find]
include = ["src*"]

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
    "mlflow>=3.10.1",
    "mypy>=1.20.0",
    "notebook>=7.5.5",
    "pre-commit>=4.5.1",
    "pytest>=9.0.2",
    "torch>=2.11.0",
    "httpx>=0.27.0",
    "rich>=13.0.0",
    "boto3>=1.28.0",
    "pytest-cov>=7.1.0",
    "ruff>=0.15.8",
    "seaborn>=0.13.2",
    "pandas-stubs>=3.0.0.260204",
]

[tool.ruff] # Configurando tools do pyprojetct. Tools sao usadas para configurar linters, formatadores e outras ferramentas de desenvolvimento.
# Numero maximo de linhas 79, seguindo padrão da documentacao ruff.
line-length = 79
exclude = ["notebooks/"]

[tool.ruff.lint]
preview = true
extend-select = ['I', 'F', 'E', 'W', 'PL', 'PT'] # Recomendacoes do dunossauro no curso de FASTApi, https://fastapidozero.dunossauro.com/estavel/01/?h=ruff#ruff

[tool.mypy]
python_version = 3.13
disallow_untyped_defs = true # Toda nova função deve ter tipo definido, seguindo boas praticas de tipagem.
exclude =[
  "notebooks/" # Excluindo notebooks do mypy, pois eles geralmente sao usados para experimentação e podem conter código mais flexivel.
]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"] # Configurando o pytest para procurar testes na pasta tests.

markers = [
    "slow: Marca para testes lentos, que podem ser executados separadamente para economizar tempo durante o desenvolvimento.",
    "fast: Marca para testes rápidos, que devem ser executados com mais frequencia durante o desenvolvimento."
]

# Configuracao de coverage para falhar se coverage estiver abaixo de 80% em src
addopts = "-v --cov=src --cov-report=term-missing --cov-fail-under=80"

filterwarnings = [
    "ignore:Type google\\._upb\\._message.*:DeprecationWarning",
]

[[tool.mypy.overrides]]
module = [
    "mlflow.*",
    "dotenv.*",
    "rich.*",
    "sklearn.*",
    "numpy.*",
    "torch.*",
    "torch",
    "torch.optim",
    "torch.optim.lr_scheduler",
    "torch.utils.data",
    "pandas",
    "pandas.*",
    "joblib",
    "joblib.*",
    "pythonjsonlogger.*",
]
ignore_missing_imports = true
